### PR TITLE
Updated gem versions

### PR DESCRIPTION
**Pull request by rsmdt**
I've been testing the newer gem versions and they seem to work like a charm. Also, zookeeper failover is working with a setup of 2 Redis nodes and 3 ZK instances - no problem with recovery.

### CODE REVIEW

**Comment by ryanlecompte** [comment]
Fantastic! It's saying that I can't automatically merge this. Can you do a full update with master and refresh the pull request? Also, are you guys using redis_failover in production yet? Thanks!

**Comment by rsmdt** [comment]
Did a rebase. Working now? We are in the process of rolling it out into production (later this week). We have multiple staging environments though with everything set-up.

**Comment by ryanlecompte** [comment]
Strange, it still says I can't merge it. I've made the changes locally here. I also relaxed the version requirement on redis-namespace: https://github.com/ryanlecompte/redis_failover/commit/6c4342ff6933e4c47eee8de3680386185576abbd

**Comment by rsmdt** [comment]
Alrighty

**Comment by ryanlecompte** [comment]
Also, happy to hear that you guys are rolling it out into production later this week. Please keep me posted, I'd love to list you guys on the wiki in a "Who is using redis_failover" page or something. Thanks!

**Comment by rsmdt** [comment]
Will talk to my client about this as they have need approve on being mentioned ;-)

**Comment by ryanlecompte** [comment]
No worries. :)

On Tue, Jun 19, 2012 at 3:25 PM, Rudolf Schmidt <
reply@reply.github.com

**Comment by rsmdt** [comment]
oops, typo in my last comment. Anywho... will stop spamming now.

**Pull request closed without merging**
