### PR TITLE
adding $stdout.sync in redis_node_manager

### PR DESCRIPTION
**Pull request by kyohsuke**
Hi, @ryanlecompte

I need to output to log file.
e.g)
nohup redis_node_manager -n aaaaaaa,bbbbbb -z cccccc,ddddddd,eeeeee > foo.log &

But the stdout is buffering, I cannot get last logs.
And the last logs outs when shutting down the node manager, though.

It requests can immediate output to log file.
It's so simple.

Prealse merge it if you like.

### CODE REVIEW

**Comment by ryanlecompte** [comment]
Looks great! Thank you. Are you using redis_failover in production yet?

**Comment by kyohsuke** [comment]
No, I'm using in staging.
But I will be use in production, soon.
Thus I send a request you.

**Comment by ryanlecompte** [comment]
Great, thanks again. Let me know if I can help, and please let me know how it works for you.

**Comment by kyohsuke** [comment]
thank you.
It product is great works for me.

**Pull request merged**
